title: Paweł Frankowski
description: Blog about Paweł Frankowski and the things he finds interesting
author: Paweł Frankowski
url: "https://blog.pawelfrankowski.eu"
lang: en
repository: pablolambo/blog
github_url: https://github.com/pablolambo
linkedin_url: https://www.linkedin.com/in/pawel-frankowski-pk/
plugins:
- jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
