title: Paweł Frankowski's blog
author: Paweł Frankowski
description: Tech blog on topics I find interesting
remote_theme: pages-themes/midnight@v0.2.0
repository: pablolambo/blog
lang: en-US
plugins:
- jekyll-remote-theme
- jekyll-seo-tag